Traceback (most recent call last):
  File "./scripts/client.py", line 63, in <module>
    main()
  File "./scripts/client.py", line 54, in main
    ai = AIDriver(game, get_ai_constructor(args.ai), ai_driver_config)
  File "./scripts/client.py", line 19, in get_ai_constructor
    ai_module = importlib.import_module('dicewars.ai.{}'.format(ai_specification))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dicewars.ai.ddt'
